services:
  test:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /src
    volumes:
      - .:/src:ro
    entrypoint: ["mvn", "clean", "verify", "-Ptest", "--no-transfer-progress"]
    environment:
      DB_URL: jdbc:mysql://test-db:3306/discopedia
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      test-db:
        condition: service_started

  test-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: discopedia
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
