services:
  test:
    image: maven:3.9.11-eclipse-temurin-21
    working_dir: /src
    volumes:
      - .:/src
    entrypoint: ["mvn", "clean", "test", "-Ptest", "--no-transfer-progress"]
    container_name: test
    environment:
      DB_URL: jdbc:mysql://test-db:3306/testdb
      DB_USERNAME: testuser
      DB_PASSWORD: testpass
    depends_on:
      test-db:
        condition: service_started
    restart: no

  test-db:
    image: mysql:8.0
    container_name: test-db
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    restart: no
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
