spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: discopedia
  config:
    import: optional:file:.env[.properties]

  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    # Data Initialization
  sql:
    init:
      mode: always

  # Server Configuration
server:
  port: ${SERVER_PORT}

  # Admin properties
  admin:
    email: admin@discopedia.com
