name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with docker-compose
        run: |
          echo "Executing testing"
          docker compose -f docker-compose-test.yml up \
            --quiet-pull \
            --abort-on-container-exit \
            --exit-code-from test

      - name: Show test results
        if: always()
        run: |
          echo "Logs from testing"
          docker compose -f docker-compose-test.yml logs test

      - name: Clean up
        if: always()
        run: |
          echo "Clean containers"
          docker compose -f docker-compose-test.yml down -v